name: Auto Deployment | School Site

on:
  push:
    branches:
    - master

jobs:
  deploytofirebase:
    name: Deploy site to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo   # Checkout and download the sites artifact previously created
        uses: actions/checkout@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting   # Deploy to FIrebase Hosting : "Catatan" Sites
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Get the token from the GitHub Repos Secrets
